name: Releases

on:
  release:
    types: [published] # stable and pre-releases

permissions:
  contents: write

jobs:
  release-abis:
    name: ABIs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create ABIs archive
        run: zip -j abis.zip abi/*.json

      - name: Upload ABIs to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view "${{ github.ref }}" || exit 1
          gh release upload "${{ github.ref }}" abis.zip
